### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by xgdgsc** [littlelib/PooledDBInterface.jl#1]
Is it possible to reconnect in place?

**Comment by littlelib** [comment]
I'm terribly sorry for such a late reply.
I'm guessing your question being is whether you can reuse the `ConnectionPool` object after closing it?

The simple answer is yes, you can reuse it even after closing it.
What `PooledDBInterface.close!` does is just close all individual connections in the pool and flush them out.
Since `PooledDBInterface.execute` will create a new connection whenever there's no connection available in the pool, you can just use `PooledDBInterface.execute` on the `ConnectionPool` object, and a new connection will be created on the fly.

**Comment by xgdgsc** [comment]
Thanks!
